Migrate to ViewPager2
readium/r2-testapp-kotlin pull request #349
Opened 2020-08-12 23:53 UTC by stevenzeck

Draft PR.  This should be merged at the same time as https://github.com/readium/r2-navigator-kotlin/pull/157.

2020-08-12 23:58 UTC, aferditamuriqi commented
Does the viewpager2 now support RTL ? When I looked at this topic last it didn't support it and it wasn't as open as viewpager to add RTL.

2020-08-13 00:04 UTC, stevenzeck commented
Yes it does, https://developer.android.com/training/animation/vp2-migration#rtl-support.

2020-08-13 00:15 UTC, aferditamuriqi commented
I have to look into my notes what the issues were. The "standard" RTL is does support, but I do remember there were some issues that couldn't be resolved. RTL and swiping issues come to mind. But I'll update here once I find my notes.

2020-08-13 04:26 UTC, stevenzeck commented
Let me know what you find out.  Do you know of any free epubs out there that are RTL to test with?

2020-08-18 01:57 UTC, stevenzeck commented
@aferditamuriqi, @mickael-menu provided me a few sample RTL epubs to test with.  I think most of the issues are going to be in the navigator rather than here in the testapp.

2020-09-17 08:18 UTC, mickael-menu requested changes
Overall I think these changes are breaking too much non-obvious (deprecation warnings) stuff in the test app.

Unfortunately at the moment the test app is too tightly coupled to the EPUB navigator internals. This makes that kind of refactoring painful since it breaks reading apps. Down the line I intend to deprecate this usage and hide the view pager from the reading app, but until then I'd like to keep things backward-compatible to avoid too many breaking migrations.

For this particular PR, there are two things that needs to be fixed to be backward-compatible:

* `R2PagerAdapter` needs to have the old API back (`mFragments`, `getItemId()`, etc.), which can internally adapt the calls to the `ViewPager2` API.
* `R2ViewPager` must still be used, we can handle this in different ways:
  * `typealias R2ViewPager = ViewPager2`. Certainly the easiest, but it might be breaking the old `R2ViewPager` API which could be used by reading apps but not the test app. Also we're exposing the whole ViewPager2 API, which might come back to bite us later.
  * Since we can't extend `ViewPager2`, we could embed it privately in a new `R2ViewPager` by composition. This is the best solution IMHO because `ViewPager2` stays private and therefore we could always switch to another implementation later. We could even potentially allow switching dynamically between ViewPager 1 and 2.

2020-09-17 08:18 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/epub/EpubActivity.kt
> +                val currentFragment = (resourcePager.adapter as R2PagerAdapter).fm.findFragmentByTag("f${resourcePager.currentItem}") as? R2EpubPageFragment
@stevenzeck Same thing, maybe there's a way to have `mFragments` and `getItemId` in the new `R2PagerAdapter` to avoid breaking this?

2020-09-17 08:18 UTC, mickael-menu commented on r2-testapp/src/main/res/layout/activity_epub.xml
> +    <androidx.viewpager2.widget.ViewPager2
@stevenzeck We should look for a way to have `R2ViewPager` work as well. I'll put more details in the general review comment.

2020-09-19 17:17 UTC, stevenzeck commented
After talking with @mickael-menu in Slack, I think it's better to hold off on this PR until all of the old R2ViewPager code is deprecated (mFragments, getCurrentFragment, etc).  I will continue making a few updates based on feedback and fixing the issues mentioned, and will keep the branch up to date as best as I can.

2021-02-16 08:11 UTC, mrifni commented
any updates on this @stevenzeck ?

2021-02-24 02:51 UTC, stevenzeck commented
@mrifni to be honest I haven't looked at this for a while.  I want to avoid having to support things in the current Readium APIs that aren't easily supported with ViewPager2.  I don't remember what those APIs are anymore, but remember talking to Mickael about them.  I'm currently rewriting the testapp to use fragments instead of activities, moving off of Anko for the UI, using Room DB, etc.

2021-02-25 16:50 UTC, mickael-menu commented
@mrifni Some relevant discussion: https://github.com/readium/r2-testapp-kotlin/discussions/394

2021-08-11 16:17 UTC, mickael-menu commented
Closing after the group decision in [today's Agenda](https://docs.google.com/document/d/18cw3QPKC8JPhHKb8bqbHqTecCSK80uDk5fmT-n07oKk). The PR is quite obsolete now and we figured using `ViewPager2` would be too limiting. For example, we can't implement the "continuous scrolling" feature with it since it's always working as a paginated view.

As an alternative, we should be able to use a `RecyclerView` with a `PagerSnapHelper`.

2021-08-11 16:17 UTC, closed without merging