Use fragments in non-reading screens and use Room database
readium/r2-testapp-kotlin pull request #403
Opened 2021-03-31 23:56 UTC by stevenzeck

This is a pretty large change and, at the time of opening this, not 100% complete.  But I want to start getting feedback.  I will sum up what I've changed, what still needs work and what I'm not crazy about.

### Changes
- All non-reader UI components that were built with Kotlin Anko have been replaced with XML layouts. This also includes the use of data binding
- The non-reader UI is composed of a single activity, MainActivity, with fragments for the screens.  This replaces having an activity for each screen
- The navigation consists of a bottom navigation menu, one for the Bookshelf for content "in" the app and Catalogs for the OPDS feeds
- All non-reader list screens use ListAdapter and DiffUtil for RecyclerViews
- Instead of the custom database, it now uses Room. This adopts the ViewModel/Repository pattern
- To facilitate this, data classes were created to represent the various entities (books, bookmarks, highlights, etc)
- A lot of code was moved to a single file, BookService.  Detailed more in the What I don't like section

### Still needs work
- OPDS group publications have not been added yet
- A lot of feedback UI hasn't been added back in yet (progress bars, snackbars, etc)
- Places that can error out are not handled properly
- Delete files no longer being used

### What I don't like
- The BookService file is quite large and should be broken up
- Due to needing to run a server, it kept erroring out because the port was being used.  I had to initialize this service in the MainActivity and grab it from that activity in the fragments
- Downloading a publication shouldn't be tied to the lifecycle of a fragment.  This was "fixed" by using a GlobalScope coroutine, but it would be better to put in a [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager).  And/or redo the OPDSDownloader to use something other than kovenant

2021-04-07 17:36 UTC, qnga reviewed
I left a few comments after a very quick look.

2021-04-07 17:36 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfFragment.kt
> +        if (ContextCompat.checkSelfPermission(requireContext(), Manifest.permission.WRITE_EXTERNAL_STORAGE)
This shouldn't be tied to the fragment view lifecycle.

2021-04-07 17:36 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfFragment.kt
> +                                file = asset.file,
I think we used to have smaller indents on continuation lines. You may try to set your IDEA to use the official Kotlin style.

2021-04-07 17:36 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
Why do you wrap the call into a new coroutine?

2021-04-07 17:36 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfViewModel.kt
> +    fun deleteBook(book: Book) = viewModelScope.launch {
Can't we be consistent by making the Fragment completely unaware of the BookService? Looks like some methods are called directly and some others are not.

2021-04-07 17:36 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/outline/OutlineFragment.kt
> +        view.findViewById<ViewPager2>(R.id.outline_pager)
??

2021-04-07 17:36 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderViewModel.kt
> +    fun deleteBookmark(id: Long) = viewModelScope.launch {
Why do you launch a coroutine here and not in `insertBookmark` ?

2021-04-07 17:36 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/db/BooksDao.kt
> +    fun getHighlightsForBook(bookId: Long): LiveData<List<Highlight>>
I'm not familiar with Room at all. Why don't you use a suspend function here? I feel like you'll be blocking the UI downstream.

2021-04-07 22:28 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfFragment.kt
> +                                file = asset.file,
I updated my Android Studio by going to Preferences > Editor > Code Style > Kotlin.  Scheme changed to Project.  Set from... changed to Kotlin style guide.  I applied this to new files created with this PR for now.  We should consider enforcing this via one of these methods:  https://kotlinlang.org/docs/code-style-migration-guide.html#migration-to-a-new-code-style.

2021-04-07 22:29 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
Good catch.  Shouldn't have done that.

2021-04-07 22:32 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfViewModel.kt
> +    fun deleteBook(book: Book) = viewModelScope.launch {
Yes it's kind of messy and needs to be cleaned up a bit.  BookService right now is a catch all for all of the non-view related code that is currently in LibraryActivity.  I can make it so the ViewModel is the intermediary so the fragment only communicates with the viewmodel.  Would that be better?  Example:

ViewModel
```
suspend fun importPublicationFromUri(uri: Uri, progressBar: ProgressBar? = null, onError: ((msg: String?) -> Unit?)? = null) {
    mBookService.importPublicationFromUri(it, progressBar, onError)
}
```

Then the fragment just calls
```
mViewModel.importPublicationFromUri(it, progressBar) { error ->
    if (error != null) {
        Snackbar.make(
            this@BookshelfFragment.requireView(),
            error,
            Snackbar.LENGTH_LONG
        ).show()
    }
}
```

Like I mention I don't like BookService and once the server is no longer needed we'll have more flexibility.  But I also don't like putting a lot of that code directly in the viewmodel either.

2021-04-07 22:33 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderViewModel.kt
> +    fun deleteBookmark(id: Long) = viewModelScope.launch {
At the moment nothing is needed from `deleteBookmark`.  Whereas `insertBookmark`, we need to know if it was successful or not to display the toast message.  I use `viewModelScope.launch` if it's a fire and forget scenario, otherwise I use suspend or LiveData observables.

2021-04-07 22:37 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/db/BooksDao.kt
> +    fun getHighlightsForBook(bookId: Long): LiveData<List<Highlight>>
Since it's returning LiveData, there is no need to use suspend.  In fact I don't _think_ Room even allows it.  It's not blocking the UI, it's. still run on a background thread.

2021-04-07 22:38 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/MainActivity.kt
> +                bookService.importPublicationFromUri(it)
I changed it to use applicationContext.

2021-04-08 07:05 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfViewModel.kt
> +    fun deleteBook(book: Book) = viewModelScope.launch {
I'm afraid this wouldn't be enough. All this stuff should be tied to a ViewModel scope or to a GlobalScope to support orientation changes. You can't pass in lambdas capturing some variables tied to an Activity, Fragment, or View lifecycle though (like the ProgressBar).
All of this needs a big refactoring and a bit of design to avoid crashes. Right now I can't see another option other than using Channels to get some feedback about commands sent to the ViewModel.

2021-04-08 07:07 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderViewModel.kt
> +    fun deleteBookmark(id: Long) = viewModelScope.launch {
Ok. I think it would be better to opt for a consistent design.

2021-04-08 07:11 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/db/BooksDao.kt
> +    fun getHighlightsForBook(bookId: Long): LiveData<List<Highlight>>
Ok, I think you're right. You won't be blocking the UI as long as you don't call LiveData.getValue, but only LiveData.observe.

2021-04-08 10:15 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/db/BooksDao.kt
> +    fun getHighlightsForBook(bookId: Long): LiveData<List<Highlight>>
`suspend` vs `LiveData` or `Flow` in Room answer two different needs:

* use `suspend` if you do a one-off request (so usually commands)
* use `LiveData`/`Flow` if you want to receive updates every time the data set changes (usually queries, especially when feeding `RecyclerView` and such)

2021-04-08 10:20 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderViewModel.kt
> +    fun deleteBookmark(id: Long) = viewModelScope.launch {
I think it's safer to let the ViewModel handles the coroutines, to avoid them being cancelled if the view starting them is closed for example.

I guess in this case, we could have an observable `LiveData` to send toast messages / events to the view.

2021-04-08 11:05 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/db/BooksDao.kt
> +    fun getHighlightsForBook(bookId: Long): LiveData<List<Highlight>>
Yeah. I think that's exactly what Steven did.

2021-04-08 11:33 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderViewModel.kt
> +    fun deleteBookmark(id: Long) = viewModelScope.launch {
That's what I meant in the above comment, excepted that I would recommend using Channels instead of LiveData:
- With Channels, you have only one stream and you queue any occurring event until a view is available to handle it once and only once.
- With LiveData, you have to have one for every command you want get some feedback from. It can quickly becomes dirty. It may even be worse if you wish to look for completion or error. 
- LiveData is not a great fit for consumable objects like messages. Depending on the place you start observing, you may have the callback called multiple times and should or should not manually check the value when the view is created (again). I think it is very error-prone.

2021-04-08 11:40 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderViewModel.kt
> +    fun deleteBookmark(id: Long) = viewModelScope.launch {
Yeah I agree, I guess the best practices will catch up once `Channel` is more widely used. I got some nasty bugs caused by `LiveData` having no backpressure and making events disappear.

2021-04-08 23:01 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderViewModel.kt
> +    fun deleteBookmark(id: Long) = viewModelScope.launch {
Pushed a change to use `Channel` for adding a bookmark success or fail toast message.

2021-04-08 23:02 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/db/BooksDao.kt
> +    fun getHighlightsForBook(bookId: Long): LiveData<List<Highlight>>
Yeah Mickael's comment is correct.  For the record if you try and use `suspend` while returning LiveData, you get an error `Error:Not sure how to convert a Cursor to this method's return type`.

2021-04-08 23:10 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfViewModel.kt
> +    fun deleteBook(book: Book) = viewModelScope.launch {
I know, that's the biggest challenge of this change.  I'll play around a bit, maybe move some functions into the utils directory, especially the extension ones.

2021-04-15 01:04 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfViewModel.kt
> +    fun deleteBook(book: Book) = viewModelScope.launch {
@qnga I moved everything back into the ViewModels and changed how the ProgressBar's are shown.  I don't care for the CatalogViewModel having both DAOs in it, nor some of the duplicate code between that and BookshelfViewModel (`addPublicationToDatabase`, `storeCoverImage`).

2021-04-20 01:45 UTC, stevenzeck commented
@qnga @mickael-menu ready for review.

2021-04-22 10:37 UTC, mickael-menu requested changes

2021-04-22 10:37 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogViewModel.kt
> +    fun insertOpds(opds: OPDS) = viewModelScope.launch {
```suggestion
    fun insertCatalog(catalog: Catalog) = viewModelScope.launch {
```

2021-04-22 10:37 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/OpdsDetailFragment.kt
> +class OpdsDetailFragment : Fragment() {
This view will only apply to OPDS catalogs, so the name is fine.

2021-04-22 10:37 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/db/Database.kt
> +abstract class BookDatabase : RoomDatabase() {
Much nicer to have a single database 👍 

```suggestion
abstract class Database : RoomDatabase() {
```

2021-04-22 10:37 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/db/OpdsDao.kt
> +interface OpdsDao {
```suggestion
interface CatalogDao {
```

2021-04-22 10:37 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderContract.kt
> +            MediaType.EPUB, MediaType.READIUM_WEBPUB_MANIFEST -> EpubActivity::class.java
You can add `MediaType.READIUM_WEBPUB` as well, for the packaged/local version.

2021-04-22 10:37 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/utils/extensions/InputStream.kt
> +    File(dir + filename)
This logic is duplicated in a few different utilities. I think this would be a nice use case for a `FileStorageService` API as well.

2021-04-22 10:37 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/utils/extensions/Uri.kt
> +*/
Our updated file header for new files is:

```kotlin
/*
 * Copyright 2021 Readium Foundation. All rights reserved.
 * Use of this source code is governed by the BSD-style license
 * available in the top-level LICENSE file of the project.
 */
```

I thought I added it in the workspace, but maybe you just moved this file?

2021-04-23 04:59 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/AudioReaderFragment.kt
> +            AudioNavigatorFragment.createFactory(publication, activity.initialLocation, this)
Fixed

2021-04-23 05:00 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/R2App.kt
> +        lateinit var R2DIRECTORY: String
Agree.  I'll create an issue for it.

2021-04-23 05:00 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfFragment.kt
> +    private lateinit var bookshelfViewModel: BookshelfViewModel
Fixed

2021-04-23 05:00 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/db/OpdsDao.kt
> +interface OpdsDao {
Fixed

2021-04-23 05:01 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderContract.kt
> +            MediaType.EPUB, MediaType.READIUM_WEBPUB_MANIFEST -> EpubActivity::class.java
Fixed

2021-04-23 05:02 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/utils/extensions/Uri.kt
> +*/
Nope this was a new file.  Is it supposed to automatically add that header when creating a new file?  Just realized that needs to be done to all new files for this PR.  I'll do that tomorrow.

2021-04-23 05:03 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfFragment.kt
> +        GlobalScope.launch {
Fixed

2021-04-23 14:54 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/utils/extensions/Uri.kt
> +*/
Yeah it's part of `r2-workspace-kotlin`'s config files, but I realized it might not be in all branches. Are you using it or your own workspace?

https://github.com/readium/r2-workspace-kotlin/blob/dev/testapp-with-lcp/.idea/fileTemplates/internal/Kotlin%20File.kt

2021-04-23 14:54 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/utils/extensions/Uri.kt
> +*/
Maybe there's a way to put them in the modules too. I just let Android Studio generate these files.

2021-04-23 15:00 UTC, mickael-menu requested changes

2021-04-23 15:00 UTC, mickael-menu commented on r2-testapp/src/main/res/xml/network_security_config.xml
> +        <domain includeSubdomains="false">s3.amazonaws.com</domain>
Could you keep these ones more clearly separated from `crl.edrlab.telesec.de`, with a small comment explaining that this is for the OPDS catalogs? To make it clear which ones should be copied in a reading app depending on the use cases. Thanks!

2021-04-24 14:13 UTC, qnga reviewed
I feel like the app is getting obvious to travel inside!

2021-04-24 18:50 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/utils/extensions/Uri.kt
> +*/
For future reference, each person needs to go into Preferences > Expand Editor > File and Code Templates > Select Project for the Scheme and click Apply.

2021-04-24 18:54 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogViewModel.kt
> +
There was a reason but I don't remember what it is anymore.  I'll initialize them all outside of and get rid of `init`.

2021-04-24 19:10 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfViewModel.kt
> +    private val context = application.applicationContext
The `application` in this case is a superclass of `ContextWrapper`, which is where it's getting `appilcationContext`.  I don't think the entire application is necessary to use for most of what's being done here, but I suppose it doesn't hurt.

2021-04-24 19:19 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogViewModel.kt
> +    val eventChannel = EventChannel(Channel<Event.FeedEvent>(Channel.BUFFERED), viewModelScope)
There is no common behavior right now no.  But at some point it would be nice to be able to download a publication from the Catalog view (via long press or something, similar to what Google Play does).  In that case a common ViewModel would make sense.  Why can't the same channel be used to send messages to communicate to both views?

2021-04-24 19:28 UTC, stevenzeck commented on r2-testapp/src/main/res/xml/network_security_config.xml
> +        <domain includeSubdomains="false">s3.amazonaws.com</domain>
Fixed

2021-04-24 19:32 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfFragment.kt
> +                                )
Fixed

2021-04-24 19:32 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/domain/model/OPDS.kt
> +data class OPDS(
Renamed almost everything from OPDS to Catalog.

2021-04-24 19:33 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogViewModel.kt
> +        storeCoverImage(publication, id.toString())
I think the latter is a better option.  I created an issue in #415

2021-04-24 19:33 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/utils/extensions/InputStream.kt
> +    File(dir + filename)
Created an issue, #415

2021-04-24 19:39 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogViewModel.kt
> +    val eventChannel = EventChannel(Channel<Event.FeedEvent>(Channel.BUFFERED), viewModelScope)
> Why can't the same channel be used to send messages to communicate to both views?

I didn't say that.

Considering your rationale, I think `eventChannel` might be called `feedEvents` and `detailChannel` `downloadEvents` or `importEvents`.

2021-04-24 19:40 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogViewModel.kt
> +        GlobalScope.launch(Dispatchers.IO) {
I forgot about this.  I was trying to get rid of the warnings about inappropriate blocking method calls (in this case it doesn't like `FileOutputStream`, `flush`, or `close`).  So I wrapped it around a GlobalScope.  But I suppose `viewModelScope.launch(Dispatchers.IO)` is the proper way to do this instead of `suspend`.

2021-04-24 20:21 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogViewModel.kt
> +    val eventChannel = EventChannel(Channel<Event.FeedEvent>(Channel.BUFFERED), viewModelScope)
Yeah I think you said in chat that they should be put in separate channels, that's where that comment came from.  I can put them in separate ViewModels if you think that's better.  I created an issue to develop an import service, which I hope will reduce the amount of code in the ViewModels when in comes to downloading and importing.  Depending on how that looks, there may not even be a need for a ViewModel in the detail fragment.

2021-04-24 20:31 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogViewModel.kt
> +    val eventChannel = EventChannel(Channel<Event.FeedEvent>(Channel.BUFFERED), viewModelScope)
If I remember correctly, that was a different case. I recommended having two channels to separate two very different concerns: emitting navigation commands to the parent Activity, and emitting feedback events to the Fragment. 

In the present case, having two channels may be justified as well because fragments are not interested in the same events. Let's keep things as they are for the moment. We'll see what's best later.

2021-04-29 16:01 UTC, mickael-menu commented
I went through regression tests and found a few issues:

* Opening an LCP-protected EPUB for the first time doesn't work and give the following error:
    > E/LcpDialogAuthentication: No valid [sender] was passed to `LcpDialogAuthentication::retrievePassphrase()`. Make sure it is an Activity, a Fragment or a View.
    * I see that the `r2Application` is given for `sender` to `Streamer.open()`. We need a view here to be able to present the passphrase dialog: `streamer.open(libraryAsset, allowUserInteraction = false, sender = r2Application)`
* When importing a new publication, and if the bookshelf spans several screens vertically, the `RecyclerView` is scrolled to the middle instead of the top, so we don't see the newly imported publication until we scroll upward.
* The Publication Details OPDS view is not scrollable, so if the content is bigger than the screen it is cropped.
* I know it's unchecked in your list, but the Facets menu is missing. Is something blocking to implement it? This feed has facets: https://catalog.feedbooks.com/featured.json

Apart from this the navigation is much smoother and all Material Design issues seem to be fixed 👍

2021-04-30 01:49 UTC, stevenzeck commented
@mickael-menu Fixed the LCP epub issue and the catalog detail screen now scrolls.

For the facets I struggled getting the PopupWindow to display nicely in a fragment with the way it is now, so I tried something different.  I built the titles and links using the native Android menu via SubMenu and MenuItem.  It works, but it's probably not the most performant or obvious to use.  I think for a future PR in making the Catalog a bit more presentable we could do something like a bottom sheet (https://material.io/components/sheets-bottom#modal-bottom-sheet).

```kotlin
override fun onPrepareOptionsMenu(menu: Menu) {
        menu.clear()
        if (showFacetMenu) {
            facets.let {
                for (i in facets.indices) {
                    val submenu = menu.addSubMenu(facets[i].title)
                    for (link in facets[i].links) {
                        val item = submenu.add(link.title)
                        item.setOnMenuItemClickListener {
                            val catalog1 = Catalog(
                                title = link.title!!,
                                href = link.href,
                                type = catalog.type
                            )
                            val bundle = bundleOf(CATALOGFEED to catalog1)
                            Navigation.findNavController(requireView())
                                .navigate(R.id.action_navigation_catalog_self, bundle)
                            true
                        }
                    }
                }
            }
        }
    }
```

2021-04-30 08:37 UTC, mickael-menu commented
Yeah that's how we do it on Aldiko. But it's definitely not a blocking issue for this PR. Thanks for taking a look

<img src="https://user-images.githubusercontent.com/58686775/116670419-fd548100-a99f-11eb-9f08-6ddfdd54b073.png" width="40%"/>

2021-04-30 13:28 UTC, merged