Replace Kovenant and Fuel with Http and Coroutines
readium/r2-testapp-kotlin pull request #419
Opened 2021-05-09 21:14 UTC by stevenzeck

Closes #404 

- Removes dependencies from Fuel and Kovenant libraries
- Fuel requests replaced by HttpRequest and HttpClient
- Kovenant Promise replaced by Try and Coroutines

Also cleaned up leftover code from #403 with building the facet popup menu

2021-05-12 10:55 UTC, mrifni commented
this looks like a good cleanup, shall we merge this PR please ?

2021-05-12 11:13 UTC, mickael-menu commented
I'll review this one this Friday

2021-05-14 11:03 UTC, mickael-menu requested changes

2021-05-14 11:03 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogFeedListFragment.kt
> +                    GlobalScope.launch {
[According to the documentation](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-global-scope/):

> Application code usually should use an application-defined `CoroutineScope`. Using `async` or `launch` on the instance of `GlobalScope` is highly discouraged.

However, I don't really see the difference between using `GlobalScope` and an application-bound `CoroutineScope`. Maybe I'm missing something. Do you have a clue @qnga?

2021-05-14 13:01 UTC, qnga commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogFeedListFragment.kt
> +                    GlobalScope.launch {
I'm not sure. Wouldn't be a reason related to termination as described [there](https://elizarov.medium.com/the-reason-to-avoid-globalscope-835337445abc)?

2021-05-14 13:20 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/catalogs/CatalogFeedListFragment.kt
> +                    GlobalScope.launch {
I'm not sure it applies since here it's a bit of a "fire and forget" situation. We don't wait for the completion nor need to cancel the job.

But this article contains an interesting comment:

> I you need a scope that lives longer than fragment / activity, you probably need `CoroutineScope(SupervisorJob() + yourDispatcher)` or just `MainScope()`. You can make it global and inject it into your long-living classes.
This gives you a scope that you can control in tests, `GlobalScope` is hard to replace / control in tests.

It might be a bit overkill for the test app but at the same time we want to promote good practices.

Anyway the coroutine actually expects the view to still be around after fetching the catalog, so I think it will crash if the catalog list if closed:

```kotlin
parseData.onFailure {
        Snackbar.make(
            requireView(),
            getString(R.string.catalog_parse_error),
            Snackbar.LENGTH_LONG
        ).show()
    }
alertDialog.dismiss()
```

Maybe we should just put the fetching code in the view model, tied to its scope, and report any error as a `Event.FeedEvent`?

2021-05-17 14:45 UTC, mickael-menu approved these changes
Thanks!

2021-05-17 14:45 UTC, merged