Fix/search UI
readium/r2-testapp-kotlin pull request #442
Opened 2021-07-13 11:58 UTC by axel-menu

2021-07-13 14:34 UTC, mickael-menu requested changes
Thanks!

There's a small issue with the first item of the list. Looks like the first header is overlapping:

![Screenshot_20210713-161659](https://user-images.githubusercontent.com/58686775/125471008-3f43dd8b-5cc6-49e9-b675-d0be4c378ab4.png)

2021-07-13 14:34 UTC, mickael-menu commented on r2-testapp/src/main/java/org/readium/r2/testapp/utils/SectionDecoration.kt
> +        fun locatorTitle(itemPos: Int): String
I think this was better as `sectionTitle()`. Your `SectionDecoration` is generic enough to be used with any `RecyclerView`, so no need to mention locators.

2021-07-15 11:22 UTC, mickael-menu approved these changes

2021-07-15 11:25 UTC, merged

2021-09-01 05:00 UTC, stevenzeck commented on r2-testapp/src/main/java/org/readium/r2/testapp/reader/ReaderViewModel.kt
> +        _searchLocators.value = emptyList()
Missed this at first, but we should null out `lastSearchQuery` here.  It wouldn't be common, but if I did hit the button to clear the search box and clear out the result list, then search for that same thing, it wouldn't do anything.